//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace HiToText.HXML
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class HiToText
    {
        public HiToText()
        {
        }

        private HiToTextEntry[] entryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entry")]
        public HiToTextEntry[] Entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntry
    {
        public HiToTextEntry()
        {
        }

        private HiToTextEntryHeader headerField;

        private HiToTextEntryMapping[] fileStructureField;

        private HiToTextEntryFieldName[] setStructureField;

        private HiToTextEntryDisplayStructure displayStructureField;

        /// <remarks/>
        public HiToTextEntryHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Mapping", IsNullable = false)]
        public HiToTextEntryMapping[] FileStructure
        {
            get
            {
                return this.fileStructureField;
            }
            set
            {
                this.fileStructureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldName", IsNullable = false)]
        public HiToTextEntryFieldName[] SetStructure
        {
            get
            {
                return this.setStructureField;
            }
            set
            {
                this.setStructureField = value;
            }
        }

        /// <remarks/>
        public HiToTextEntryDisplayStructure DisplayStructure
        {
            get
            {
                return this.displayStructureField;
            }
            set
            {
                this.displayStructureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeader
    {
        public HiToTextEntryHeader()
        {
        }

        private string[] gamesField;

        private string[] fieldsField;

        //private string[] extensionsField;
        private HiToTextEntryHeaderName[] extensionsField;

        private HiToTextEntryHeaderTextParameters textParametersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Name", IsNullable = false)]
        public string[] Games
        {
            get
            {
                return this.gamesField;
            }
            set
            {
                this.gamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Name", IsNullable = false)]
        public string[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Name", IsNullable = false)]
        public HiToTextEntryHeaderName[] Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public HiToTextEntryHeaderTextParameters TextParameters
        {
            get
            {
                return this.textParametersField;
            }
            set
            {
                this.textParametersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderName
    {
        public HiToTextEntryHeaderName()
        {
        }

        private int numberOfBytesField;

        private bool numberOfBytesFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfBytes
        {
            get
            {
                return this.numberOfBytesField;
            }
            set
            {
                this.numberOfBytesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfBytesSpecified
        {
            get
            {
                return this.numberOfBytesFieldSpecified;
            }
            set
            {
                this.numberOfBytesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParameters
    {
        public HiToTextEntryHeaderTextParameters()
        {
        }

        private HiToTextEntryHeaderTextParametersFormats formats;

        private HiToTextEntryHeaderTextParametersOffsets offsets;

        private HiToTextEntryHeaderTextParametersSpecialMapping specialMapping;

        private HiToTextEntryHeaderTextParametersSwitchMaps switchMaps;

        private int byteSkipAmountField;

        private bool byteSkipAmountFieldSpecified;

        private int byteStartField;

        private bool byteStartFieldSpecified;

        private string byteSkipDataField;

        [System.Xml.Serialization.XmlElementAttribute("Formats", typeof(HiToTextEntryHeaderTextParametersFormats))]
        public HiToTextEntryHeaderTextParametersFormats Formats
        {
            get
            {
                return this.formats;
            }
            set
            {
                this.formats = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Offsets", typeof(HiToTextEntryHeaderTextParametersOffsets))]
        public HiToTextEntryHeaderTextParametersOffsets Offsets
        {
            get
            {
                return this.offsets;
            }
            set
            {
                this.offsets = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("SpecialMapping", typeof(HiToTextEntryHeaderTextParametersSpecialMapping))]
        public HiToTextEntryHeaderTextParametersSpecialMapping SpecialMapping
        {
            get
            {
                return this.specialMapping;
            }
            set
            {
                this.specialMapping = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("SwitchMaps", typeof(HiToTextEntryHeaderTextParametersSwitchMaps))]
        public HiToTextEntryHeaderTextParametersSwitchMaps SwitchMaps
        {
            get
            {
                return this.switchMaps;
            }
            set
            {
                this.switchMaps = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ByteSkipAmount
        {
            get
            {
                return this.byteSkipAmountField;
            }
            set
            {
                this.byteSkipAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ByteSkipAmountSpecified
        {
            get
            {
                return this.byteSkipAmountFieldSpecified;
            }
            set
            {
                this.byteSkipAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ByteStart
        {
            get
            {
                return this.byteStartField;
            }
            set
            {
                this.byteStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ByteStartSpecified
        {
            get
            {
                return this.byteStartFieldSpecified;
            }
            set
            {
                this.byteStartFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ByteSkipData
        {
            get
            {
                return this.byteSkipDataField;
            }
            set
            {
                this.byteSkipDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersFormats
    {
        public HiToTextEntryHeaderTextParametersFormats()
        {
        }

        private string[] nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string[] Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersOffsets
    {
        public HiToTextEntryHeaderTextParametersOffsets()
        {
        }

        private HiToTextEntryHeaderTextParametersOffsetsOffset[] offsetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Offset")]
        public HiToTextEntryHeaderTextParametersOffsetsOffset[] Offset
        {
            get
            {
                return this.offsetField;
            }
            set
            {
                this.offsetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersOffsetsOffset
    {
        public HiToTextEntryHeaderTextParametersOffsetsOffset()
        {
        }

        private string typeField;

        private string startByteField;

        private byte skipModifierField;

        private bool skipModifierFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartByte
        {
            get
            {
                return this.startByteField;
            }
            set
            {
                this.startByteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte SkipModifier
        {
            get
            {
                return this.skipModifierField;
            }
            set
            {
                this.skipModifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SkipModifierSpecified
        {
            get
            {
                return this.skipModifierFieldSpecified;
            }
            set
            {
                this.skipModifierFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersSpecialMapping
    {
        public HiToTextEntryHeaderTextParametersSpecialMapping()
        {
        }

        private HiToTextEntryHeaderTextParametersSpecialMappingMap[] mapField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Map")]
        public HiToTextEntryHeaderTextParametersSpecialMappingMap[] Map
        {
            get
            {
                return this.mapField;
            }
            set
            {
                this.mapField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersSpecialMappingMap
    {
        public HiToTextEntryHeaderTextParametersSpecialMappingMap()
        {
        }

        private string charField;

        private string byteField;

        private string commentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Char
        {
            get
            {
                return this.charField;
            }
            set
            {
                this.charField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Byte
        {
            get
            {
                return this.byteField;
            }
            set
            {
                this.byteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersSwitchMaps
    {
        public HiToTextEntryHeaderTextParametersSwitchMaps()
        {
        }

        private HiToTextEntryHeaderTextParametersSwitchMapsSwitchMap[] switchMapField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SwitchMap")]
        public HiToTextEntryHeaderTextParametersSwitchMapsSwitchMap[] SwitchMap
        {
            get
            {
                return this.switchMapField;
            }
            set
            {
                this.switchMapField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersSwitchMapsSwitchMap
    {
        public HiToTextEntryHeaderTextParametersSwitchMapsSwitchMap()
        {
        }

        private HiToTextEntryHeaderTextParametersSwitchMapsSwitchMapMapping[] mappingField;

        private string nameField;

        private string defaultOneField;

        private string defaultManyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mapping")]
        public HiToTextEntryHeaderTextParametersSwitchMapsSwitchMapMapping[] Mapping
        {
            get
            {
                return this.mappingField;
            }
            set
            {
                this.mappingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultOne
        {
            get
            {
                return this.defaultOneField;
            }
            set
            {
                this.defaultOneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultMany
        {
            get
            {
                return this.defaultManyField;
            }
            set
            {
                this.defaultManyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryHeaderTextParametersSwitchMapsSwitchMapMapping
    {
        public HiToTextEntryHeaderTextParametersSwitchMapsSwitchMapMapping()
        {
        }

        private string oneField;

        private string manyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string One
        {
            get
            {
                return this.oneField;
            }
            set
            {
                this.oneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Many
        {
            get
            {
                return this.manyField;
            }
            set
            {
                this.manyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryMapping
    {
        public HiToTextEntryMapping()
        {
        }

        private HiToTextEntryMappingEntry[] entryField;

        private int numberOfBlocksField;

        private string orderingField;

        private int startField;

        private bool startFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entry")]
        public HiToTextEntryMappingEntry[] Entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfBlocks
        {
            get
            {
                return this.numberOfBlocksField;
            }
            set
            {
                this.numberOfBlocksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ordering
        {
            get
            {
                return this.orderingField;
            }
            set
            {
                this.orderingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartSpecified
        {
            get
            {
                return this.startFieldSpecified;
            }
            set
            {
                this.startFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryMappingEntry
    {
        public HiToTextEntryMappingEntry()
        {
        }

        private string nameField;

        private int lengthField;

        private string scatterPatternField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ScatterPattern
        {
            get
            {
                return this.scatterPatternField;
            }
            set
            {
                this.scatterPatternField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryFieldName
    {
        public HiToTextEntryFieldName()
        {
        }

        private HiToTextEntryFieldNameSpecialUtilization[] specialUtilizationField;

        private string nameField;

        private string fieldTypeField;

        private string conversionTypeField;

        private string externalWrapperField;

        private string positionField;

        private byte constantField;

        private bool constantFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SpecialUtilization")]
        public HiToTextEntryFieldNameSpecialUtilization[] SpecialUtilization
        {
            get
            {
                return this.specialUtilizationField;
            }
            set
            {
                this.specialUtilizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FieldType
        {
            get
            {
                return this.fieldTypeField;
            }
            set
            {
                this.fieldTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConversionType
        {
            get
            {
                return this.conversionTypeField;
            }
            set
            {
                this.conversionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExternalWrapper
        {
            get
            {
                return this.externalWrapperField;
            }
            set
            {
                this.externalWrapperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Constant
        {
            get
            {
                return this.constantField;
            }
            set
            {
                this.constantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConstantSpecified
        {
            get
            {
                return this.constantFieldSpecified;
            }
            set
            {
                this.constantFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryFieldNameSpecialUtilization
    {
        public HiToTextEntryFieldNameSpecialUtilization()
        {
        }

        private string functionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Function
        {
            get
            {
                return this.functionField;
            }
            set
            {
                this.functionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryDisplayStructure
    {
        public HiToTextEntryDisplayStructure()
        {
        }

        private HiToTextEntryDisplayStructureFieldName[] fieldNameField;

        private byte numOfDisplayedEntriesField;

        private bool numOfDisplayedEntriesFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldName")]
        public HiToTextEntryDisplayStructureFieldName[] FieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NumOfDisplayedEntries
        {
            get
            {
                return this.numOfDisplayedEntriesField;
            }
            set
            {
                this.numOfDisplayedEntriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumOfDisplayedEntriesSpecified
        {
            get
            {
                return this.numOfDisplayedEntriesFieldSpecified;
            }
            set
            {
                this.numOfDisplayedEntriesFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HiToTextEntryDisplayStructureFieldName
    {
        public HiToTextEntryDisplayStructureFieldName()
        {
        }

        private string nameField;

        private string conversionTypeField;

        private string operatorField;

        private string customNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConversionType
        {
            get
            {
                return this.conversionTypeField;
            }
            set
            {
                this.conversionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomName
        {
            get
            {
                return this.customNameField;
            }
            set
            {
                this.customNameField = value;
            }
        }
    }
}
