all: Program.exe

Program.exe:	Program.cs  Formatting.cs Hiscore.cs  Games/*cs Utils/*cs HXML/*cs Generic/*cs Games/Alternate/trackfld_090410.cs
	mcs Program.cs  Formatting.cs Hiscore.cs  Games/*cs Utils/*cs HXML/*cs Generic/*cs Games/Alternate/trackfld_090410.cs
